/**
 * Curated high-definition 16:9 stock footage library
 * videoUrl uses 'lavfi:' prefix = generated by FFmpeg (no download needed)
 * or real HTTP URLs from Pexels CDN (verified accessible)
 */

// Special scheme handled by render server: 'lavfi:<ffmpeg_lavfi_filter>'
export const STOCK_COLLECTION = [
	// Technology & AI
	{
		id: 'tech-1',
		title: 'Futuristic AI Neural Network & Data Stream',
		category: 'tech',
		tags: ['ai', 'artificial intelligence', 'technology', 'network', 'cyber', 'data', 'future', 'digital', 'neural'],
		thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'lavfi:color=c=0x030b1a:size=1920x1080:rate=30,hue=h=t*15:s=0.8',
		duration: 15,
		author: 'Generated'
	},
	{
		id: 'tech-2',
		title: 'Cyberpunk Neon City Night & Digital Waves',
		category: 'tech',
		tags: ['cyberpunk', 'city', 'neon', 'night', 'futuristic', 'computer', 'code', 'matrix', 'circuit'],
		thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'lavfi:color=c=0x0a001a:size=1920x1080:rate=30,hue=h=t*25+180:s=1',
		duration: 15,
		author: 'Generated'
	},
	{
		id: 'tech-3',
		title: 'Microchip Processor & Hardware Innovation',
		category: 'tech',
		tags: ['microchip', 'processor', 'hardware', 'quantum', 'innovation', 'robot', 'automation'],
		thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'https://videos.pexels.com/video-files/3141207/3141207-uhd_2560_1440_25fps.mp4',
		duration: 60,
		author: 'Pexels'
	},

	// Nature & Planet
	{
		id: 'nature-1',
		title: 'Cinematic Mountain Peaks at Sunrise Drone',
		category: 'nature',
		tags: ['mountain', 'nature', 'sunrise', 'drone', 'landscape', 'sky', 'clouds', 'earth', 'travel'],
		thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'https://videos.pexels.com/video-files/3209828/3209828-uhd_2560_1440_25fps.mp4',
		duration: 60,
		author: 'Pexels'
	},
	{
		id: 'nature-2',
		title: 'Majestic Ocean Waves & Golden Sunset',
		category: 'nature',
		tags: ['ocean', 'sea', 'waves', 'sunset', 'water', 'beach', 'calm', 'peaceful', 'horizon'],
		thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'lavfi:color=c=0x1a0800:size=1920x1080:rate=30,hue=h=t*10+30:s=0.9',
		duration: 60,
		author: 'Generated'
	},

	// Space & Universe
	{
		id: 'space-1',
		title: 'Deep Cosmic Nebula, Stars & Galaxies',
		category: 'space',
		tags: ['space', 'universe', 'galaxy', 'stars', 'nebula', 'astronomy', 'cosmos', 'telescope', 'planets'],
		thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'lavfi:color=c=0x000008:size=1920x1080:rate=30,hue=h=t*5+240:s=0.6',
		duration: 60,
		author: 'Generated'
	},

	// Business, Finance & Productivity
	{
		id: 'business-1',
		title: 'Stock Market Candlesticks & Financial Growth',
		category: 'business',
		tags: ['finance', 'money', 'stock market', 'trading', 'crypto', 'investment', 'wealth', 'chart', 'growth', 'economy'],
		thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'lavfi:color=c=0x001a08:size=1920x1080:rate=30,hue=h=t*12+120:s=0.85',
		duration: 30,
		author: 'Generated'
	},
	{
		id: 'business-2',
		title: 'Modern High-Rise Metropolis & Busy Skyline',
		category: 'business',
		tags: ['city', 'skyline', 'business', 'metropolis', 'success', 'office', 'career', 'urban', 'work'],
		thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'lavfi:color=c=0x080a1a:size=1920x1080:rate=30,hue=h=t*8+200:s=0.75',
		duration: 15,
		author: 'Generated'
	},

	// Mindset, Psychology & Mystery
	{
		id: 'mindset-1',
		title: 'Hourglass Passing of Time & Focus',
		category: 'mindset',
		tags: ['time', 'habits', 'psychology', 'focus', 'mindset', 'meditation', 'discipline', 'brain', 'thinking'],
		thumbnail: 'https://images.unsplash.com/photo-1501139083538-0139583c060f?w=800&auto=format&fit=crop&q=80',
		videoUrl: 'lavfi:color=c=0x0f0a1a:size=1920x1080:rate=30,hue=h=t*6+280:s=0.7',
		duration: 45,
		author: 'Generated'
	}
];

/**
 * Find best matching stock footage by query keywords
 */
export function findMatchingStockVideo(query) {
	if (!query) return STOCK_COLLECTION[0];
	
	const qLower = query.toLowerCase();
	const words = qLower.split(/\s+/).filter(w => w.length > 2);
	
	let bestMatch = STOCK_COLLECTION[0];
	let highestScore = -1;

	for (const item of STOCK_COLLECTION) {
		let score = 0;
		for (const word of words) {
			if (item.category.includes(word)) score += 5;
			for (const tag of item.tags) {
				if (tag.includes(word) || word.includes(tag)) score += 3;
			}
			if (item.title.toLowerCase().includes(word)) score += 2;
		}

		if (score > highestScore) {
			highestScore = score;
			bestMatch = item;
		}
	}

	return bestMatch;
}
